const fs = require('fs')
fs.mkdirSync('temp')
fs.writeFileSync('temp/bio.txt','My name is Rushikesh\n')
fs.appendFileSync('temp/bio.txt',`I'm a VIITian`)
const data = fs.readFileSync('temp/bio.txt','utf-8')
console.log(data)
fs.renameSync("temp/bio.txt","temp/mybio.txt")
fs.unlinkSync('temp/mybio.txt')
fs.rmdirSync('temp')
